TOPDIR         ?= .
LIB_MAKE_TYPE   = shared
#LIB_MAKE_TYPE ?=static
MAKE_TYPE       = $(LIB_MAKE_TYPE)
LIB_PREFIX      = lib
BUILD_PATH      = $(TOPDIR)/build

include $(Function_Data_Path)/MakeScripts/make.conf

clean_tmp:
	@rm $(BUILD_PATH) -r
